// src/components/only-view-model.tsx
import { observer } from 'mobx-react-lite';
import type { ReactNode } from 'react';
import type { Class, IsPartial } from 'yummies/types';

import {
  type UseCreateViewModelConfig,
  useCreateViewModel,
} from '../hooks/index.js';
import type { AnyViewModel } from '../view-model/index.js';

export type OnlyViewModelProps<TViewModel extends AnyViewModel> = {
  model: Class<TViewModel>;
  children?: ReactNode | ((model: TViewModel) => ReactNode);
} & (IsPartial<TViewModel['payload']> extends true
  ? {
      payload?: TViewModel['payload'];
      config?: UseCreateViewModelConfig<TViewModel>;
    }
  : {
      payload: TViewModel['payload'];
      config?: UseCreateViewModelConfig<TViewModel>;
    });

export const OnlyViewModel = observer(
  <TViewModel extends AnyViewModel>({
    model,
    config,
    payload,
    children,
  }: OnlyViewModelProps<TViewModel>) => {
    const vm = useCreateViewModel(model, payload, config);

    if (!vm.isMounted) {
      return null;
    }

    if (typeof children === 'function') {
      return children(vm);
    }
    return <>{children}</>;
  },
);

// packages/solid/src/components/only-view-model.tsx
import type { AnyViewModel } from 'mobx-view-model';
import { Show, type JSX } from 'solid-js';
import type { Class, IsPartial } from 'yummies/types';
import {
  type UseCreateViewModelConfig,
  useCreateViewModel,
} from '../hooks/index.js';

export type OnlyViewModelProps<TViewModel extends AnyViewModel> = {
  model: Class<TViewModel>;
  children?: JSX.Element | ((model: TViewModel) => JSX.Element);
} & (IsPartial<TViewModel['payload']> extends true
  ? {
      payload?: TViewModel['payload'];
      config?: UseCreateViewModelConfig<TViewModel>;
    }
  : {
      payload: TViewModel['payload'];
      config?: UseCreateViewModelConfig<TViewModel>;
    });

export const OnlyViewModel = <TViewModel extends AnyViewModel>(
  props: OnlyViewModelProps<TViewModel>,
) => {
  const vm = useCreateViewModel(
    props.model,
    () => props.payload,
    props.config,
  );

  const Content = () =>
    typeof props.children === 'function'
      ? props.children(vm)
      : props.children;

  return (
    <Show when={() => vm.isMounted}>
      <Content />
    </Show>
  );
};
