// src/components/view-models-provider.tsx
import type { ComponentType, ReactNode } from 'react';
import { ViewModelsContext } from '../contexts/index.js';
import type { ViewModelStore } from '../view-model/index.js';

export const ViewModelsProvider =
  ViewModelsContext.Provider as unknown as ComponentType<{
    value: ViewModelStore;
    children?: ReactNode;
  }>;

// packages/solid/src/components/view-models-provider.tsx
import type { ViewModelStore } from 'mobx-view-model';
import type { ParentComponent } from 'solid-js';
import { ViewModelsContext } from '../contexts/index.js';

export const ViewModelsProvider: ParentComponent<{
  value: ViewModelStore;
}> = (props) => (
  <ViewModelsContext.Provider value={props.value}>
    {props.children}
  </ViewModelsContext.Provider>
);
