// packages/core/src/react/contexts/active-view-context.ts
import type { AnyViewModel, AnyViewModelSimple } from '../../core.js';
import { createContext } from 'react';

declare const globalThis: any

globalThis[Symbol.for('mobx-view-model/active-vm')] ??= createContext<
  AnyViewModel | AnyViewModelSimple
>(null as any); 

// will contains the view model
export const ActiveViewModelContext: React.Context<AnyViewModelSimple | AnyViewModel> =
  globalThis[Symbol.for('mobx-view-model/active-vm')]

// packages/solid/src/contexts/active-view-context.ts
import { _internals, type AnyViewModel, type AnyViewModelSimple } from 'mobx-view-model';
import { createContext } from 'solid-js';

const symbol = Symbol.for(`${_internals.key}/avm-ctx`);

type Context = ReturnType<typeof createContext<AnyViewModel | AnyViewModelSimple>>;

declare const globalThis: { [symbol]?: Context }

/** Contains the active (parent) view model for nested VMs. */
globalThis[symbol] ??= createContext(null as any) as Context;

export const ActiveViewModelContext = globalThis[symbol];
