// packages/solid/src/components/active-view-model-provider.tsx
import type { AnyViewModel, AnyViewModelSimple } from 'mobx-view-model';
import type { ParentComponent } from 'solid-js';
import { ActiveViewModelContext } from '../contexts/index.js';

/**
 * Provider for `ActiveViewModelContext`.
 * Not recommended for public usage — prefer `withViewModel`.
 */
export const ActiveViewModelProvider: ParentComponent<{
  value: AnyViewModel | AnyViewModelSimple;
}> = (props) => (
  <ActiveViewModelContext.Provider value={props.value}>
    {props.children}
  </ActiveViewModelContext.Provider>
);

// packages/core/src/components/active-view-model-provider.tsx
import type { AnyViewModel, AnyViewModelSimple } from 'mobx-view-model/core';
import { ActiveViewModelContext } from '../contexts/index.js';

/**
 * This is a provider for the `ActiveViewModelContext`.
 * This HOC is not recommended for public usage.
 * Better to use `withViewModel` HOC.
 */
export const ActiveViewModelProvider =
  ActiveViewModelContext.Provider as unknown as React.ComponentType<{
    value: AnyViewModel | AnyViewModelSimple;
    children?: React.ReactNode;   
  }>;
